In [2]:
import numpy as np

In [3]:
# LambddaCDM
# 1. Define the standard deviations (1-sigma errors)
# For l_A, we use 0.0895 (the average of the asymmetric +0.089, -0.090 errors)
std_devs = np.array([0.0046, 0.0895, 0.00015])

# 2. Define the normalized correlation matrix (rho)
rho = np.array([
    [ 1.0,   0.46, -0.66],
    [ 0.46,  1.0,  -0.33],
    [-0.66, -0.33,  1.0]
])

# 3. Create the diagonal matrix D
# np.diag() places the standard deviations on the main diagonal and zeros everywhere else
D = np.diag(std_devs)

# 4. Calculate the unnormalized covariance matrix (Sigma)
# The '@' operator in Python is used for matrix multiplication
covariance_matrix = D @ rho @ D

# 5. Calculate the Inverse Covariance Matrix (Precision Matrix)
inverse_covariance_matrix = np.linalg.inv(covariance_matrix)

# Display the results with formatted output for readability
print("Unnormalized Covariance Matrix:")
np.set_printoptions(suppress=True, precision=8) # Keeps numbers from printing in scientific notation if possible
print(covariance_matrix)

# Display the results
print("Inverse Covariance Matrix:")
np.set_printoptions(suppress=True, precision=2)
print(inverse_covariance_matrix)

Unnormalized Covariance Matrix:
[[ 0.00002116  0.00018938 -0.00000046]
 [ 0.00018938  0.00801025 -0.00000443]
 [-0.00000046 -0.00000443  0.00000002]]
Inverse Covariance Matrix:
[[   94789.      -1324.16  1657802.22]
 [   -1324.16      158.59     4426.26]
 [ 1657802.22     4426.26 78869891.69]]


In [6]:
np.outer(std_devs, std_devs)*rho

array([[ 0.  ,  0.  , -0.  ],
       [ 0.  ,  0.01, -0.  ],
       [-0.  , -0.  ,  0.  ]])

In [7]:
# wCDM model
# 1. Define the standard deviations (1-sigma errors)
# For l_A, we use 0.0895 (the average of the asymmetric +0.089, -0.090 errors)
std_devs = np.array([0.0046, 0.0895, 0.00015])

# 2. Define the normalized correlation matrix (rho)
rho = np.array([
    [ 1.0,   0.47, -0.66],
    [ 0.47,  1.0,  -0.34],
    [-0.66, -0.34,  1.0]
])

# 3. Create the diagonal matrix D
# np.diag() places the standard deviations on the main diagonal and zeros everywhere else
D = np.diag(std_devs)

# 4. Calculate the unnormalized covariance matrix (Sigma)
# The '@' operator in Python is used for matrix multiplication
covariance_matrix = D @ rho @ D

# 5. Calculate the Inverse Covariance Matrix (Precision Matrix)
inverse_covariance_matrix = np.linalg.inv(covariance_matrix)

# Display the results with formatted output for readability
print("Unnormalized Covariance Matrix:")
np.set_printoptions(suppress=True, precision=8) # Keeps numbers from printing in scientific notation if possible
print(covariance_matrix)

# Display the results
print("Inverse Covariance Matrix:")
np.set_printoptions(suppress=True, precision=2)
print(inverse_covariance_matrix)

Unnormalized Covariance Matrix:
[[ 0.00002116  0.0001935  -0.00000046]
 [ 0.0001935   0.00801025 -0.00000456]
 [-0.00000046 -0.00000456  0.00000002]]
Inverse Covariance Matrix:
[[   95242.51    -1359.39  1651932.7 ]
 [   -1359.39      160.56     5058.24]
 [ 1651932.7      5058.24 78905711.17]]
